<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_sign-username</name>
   <tag></tag>
   <elementGuidId>88bc989f-296d-4b0e-bb7e-ddfa301b7b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Username:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>573dfd20-8e3d-4ee1-aaa7-4ef31c43844a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a53522ac-ec13-4ff7-adf5-febe04489129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9116e491-3759-488e-aea3-856a0686bbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign-username</value>
      <webElementGuid>fab323ed-a7f2-49d4-9860-fdfb7cd2ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign-username&quot;)</value>
      <webElementGuid>f4f038c3-5cdb-46eb-9417-e2bbf94f05a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign-username']</value>
      <webElementGuid>491627e9-d617-4f46-83e7-f1cd1ff60f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signInModal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>3c9d4206-39ba-415c-991a-fd9dc8e1eb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/form/div/input</value>
      <webElementGuid>d207e72d-acd8-490d-b302-e5acc54de002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sign-username']</value>
      <webElementGuid>8dd8d4b9-3404-4bd2-9133-5b61b8c64cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
